apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    # The ACME server V2 URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    # email: dns-admin@freedomdebtrelief.com
    email: ccpswe@freedomdebtrelief.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-secret
    # Enable the HTTP-01 challenge provider
    http01: {}
