apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      role: mongo
      environment: test
      replicaset: MainRepSet
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        replicaset: MainRepSet
    spec:
      containers:
        - name: mongod-container
          image: mongo
          command:
            - 'numactl'
            - '--interleave=all'
            - 'mongod'
            - '--bind_ip'
            - '0.0.0.0'
            - '--replSet'
            - 'MainRepSet'
            - '--auth'
            - '--clusterAuthMode'
            - 'keyFile'
            - '--keyFile'
            - '/etc/secrets-volume/mongo-secret'
            - '--setParameter'
            - 'authenticationMechanisms=SCRAM-SHA-1'
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
      volumes:
        - name: secrets-volume
          secret:
            secretName: mongo
            defaultMode: 256
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage-claim
        annotations:
          volume.beta.kubernetes.io/storage-class: 'fast'
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 50Gi
